{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE FlexibleContexts      #-}
{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE ScopedTypeVariables   #-}
{-# LANGUAGE TypeApplications      #-}
{-# LANGUAGE TypeFamilies          #-}
{-# LANGUAGE TypeOperators         #-}
{-# LANGUAGE UndecidableInstances  #-}
{-# OPTIONS_GHC -Wno-orphans #-}

-- | The 'Arbitrary' instances the test suites share. Deliberately orphan:
-- they belong to neither QuickCheck nor the library.
module Test.Arbitrary
  (
  ) where

import           Data.Grid.Sized

import           Control.Lens     (review)
import           Data.Proxy
import           Generics.SOP     hiding (S, Z)
import qualified GHC.Generics     as GHC
import           GHC.TypeLits
import           Test.QuickCheck  (Arbitrary (..), Arbitrary1 (..), Gen,
                                   chooseInt)

-- | Pick one position on an axis, in constant time -- rather than
-- materialising the whole domain to draw a single sample.
--
-- @1 <= n@ is load-bearing: it is what gives 'maxBound', and an axis of size
-- zero has no inhabitant to return.
genOrdinal :: forall n. (1 <= n, KnownNat n) => Gen (Ordinal n)
genOrdinal =
  unsafeOrdinal <$> chooseInt (0, ordinalToNum (maxBound :: Ordinal n))

instance (1 <= n, KnownNat n) => Arbitrary (Ordinal n) where
  arbitrary = genOrdinal

instance (1 <= n, KnownNat n) => Arbitrary (Periodic n) where
  arbitrary = Periodic <$> genOrdinal

instance (1 <= n, KnownNat n) => Arbitrary (Clamped n) where
  arbitrary = Clamped <$> genOrdinal

instance (1 <= n, KnownNat n) => Arbitrary (Reflective n) where
  arbitrary = Reflective <$> genOrdinal

instance (1 <= n, KnownNat n) => Arbitrary (Reflect101 n) where
  arbitrary = Reflect101 <$> genOrdinal

instance (All Arbitrary cs, SListI cs) => Arbitrary (NP I cs) where
  arbitrary = hsequence (hcpure (Proxy @Arbitrary) arbitrary)

-- | Via the @NP@ rather than by drawing a flat position, so every axis is
-- generated by its own 'Arbitrary' and shrinking stays per-axis.
instance (IsCoordList cs, All Arbitrary cs) => Arbitrary (Coord cs) where
  arbitrary = review _WrappedCoord <$> arbitrary

instance (All Arbitrary ds, SListI ds) => Arbitrary (Delta ds) where
  arbitrary = Delta <$> arbitrary

instance AllSizedKnown cs => Arbitrary1 (Grid cs) where
  liftArbitrary g = sequenceA (pure g)

instance (AllSizedKnown cs, Arbitrary a) => Arbitrary (Grid cs a) where
  arbitrary = liftArbitrary arbitrary

-- | 'quickcheck-classes'' 'genericLaws' draws from the generic
-- representation directly, not from @a@; routing through the already-tested
-- 'Arbitrary' for 'Grid' and 'GHC.from' is simpler than matching the
-- generated 'M1'\/'K1' structure by hand.
--
-- The head is the bare type variable @r@, with the concrete 'GHC.Rep' pinned
-- down by the equality constraint instead: 'GHC.Rep' is a type family, and
-- GHC never accepts one directly in an instance head, ground or not.
instance {-# OVERLAPPABLE #-} (r ~ GHC.Rep (Grid '[ Periodic 10, Periodic 11] Int) ()) =>
         Arbitrary r where
  arbitrary = GHC.from <$> (arbitrary :: Gen (Grid '[ Periodic 10, Periodic 11] Int))

-- | A grid and a focus drawn independently: the comonad laws have to hold for
-- every focus, not just a canonical one.
instance (AllSizedKnown cs, IsCoordList cs, All Arbitrary cs, Arbitrary a) =>
         Arbitrary (FocusedGrid cs a) where
  arbitrary = FocusedGrid <$> arbitrary <*> arbitrary
